### PR TITLE
Fix "Call to a member function getMethod() on bool"

### LINKED ISSUE #112: Call to a member function getMethod() on bool (AdminOrderShowMenuListener.php)
When I visit the admin order page (`/admin/orders/xx`) of an order without payments, I get the following error:
```
Error:
Call to a member function getMethod() on bool

  at vendor/bitbag/mollie-plugin/src/Menu/AdminOrderShowMenuListener.php:42
  at BitBag\SyliusMolliePlugin\Menu\AdminOrderShowMenuListener->addPaymentlinkButton()
```

I'm using v3.3.4 of the plugin with v1.8.5 of Sylius.

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #112.

### CODE REVIEW

File: src/Menu/AdminOrderShowMenuListener.php [hunk 1]
```diff
@@ -34,6 +34,10 @@ public function addPaymentlinkButton(OrderShowMenuBuilderEvent $event): void
         /** @var PaymentInterface $payment */
         $payment = $order->getPayments()->last();
 
+        if ($payment === false) {
```
Comment (daniel8702) [inline src/Menu/AdminOrderShowMenuListener.php:37]:
``` suggestion
        if (false === $payment) {
```

**Review by daniel8702 — CHANGES_REQUESTED** [review]

**Review by daniel8702 — APPROVED** [review]
