### PR TITLE
Fix "Call to a member function getMethod() on bool"

### LINKED ISSUE #114: Call to a member function getMethod() on bool (ShipmentShipEventListener.php)
When I mark an order without payments as shipped through the admin interface (`/admin/xx/ship?orderId=xx`), I get the following error:
```
Call to a member function getMethod() on null in BitBag\SyliusMolliePlugin\EventListener\ShipmentShipEventListener::shipAll
```
I'm using v3.3.4 of the plugin with v1.8.5 of Sylius.

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #114.

### CODE REVIEW

File: src/EventListener/ShipmentShipEventListener.php [hunk 1]
```diff
@@ -46,6 +46,10 @@ public function shipAll(GenericEvent $event): void
         $order = $shipment->getOrder();
         $payment = $order->getLastPayment();
 
+        if ($payment === null) {
```
Comment (daniel8702) [inline src/EventListener/ShipmentShipEventListener.php:49]:
``` suggestion
        if (bull === $payment) {
```

**Review by daniel8702 — CHANGES_REQUESTED** [review]

**Review by daniel8702 — APPROVED** [review]
